version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  build:
    docker: cimg/node:current
  steps:
    - checkout
    - run: echo "installing dependencies"
    - run: npm ci
    - run: echo "installing lint"
    - run: npm run lint
    - run: echo "running ts check"
    - run: npm run build -- --noEmit
    - run: echo "Building project"
    - run: CI=true npm run build

workflows:
  version: 2.1
  build_only:
    jobs:
      - build
