version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: echo "Installing dependencies"
      - run: corepack enable pnpm
      - run: echo "Installing dependencies"
      - run: pnpm install --no-lockfile
      - run: echo "Generating Prisma Client"
      - run: pnpm prisma generate
      # - run: echo "Linting"
      # - run: npm run lint
      # - run: echo "Type checking"
      # - run: pnpm exec tsc --noEmit
      - run: echo "Building project"
      - run: CI=true pnpm run build

workflows:
  version: 2.1
  build_only:
    jobs:
      - build
